### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by 1423444** [1423444/Internet-Explorers#2]
##### index.html

Ich hab gedacht, man muss Umlaute mit Code einfügen.
Muss man die Umlaute doch direkt eingeben?

**Comment by 1423444** [comment]
@tjuenemann falls du schon kannst :)

**Comment by 1423444** [comment]
@CodeKittey Wir stoßen hier auf die Problematik, dass in unserem [HTML-Dokument](https://github.com/1423444/Internet-Explorers/blob/master/Internet%20Explorers/Meilenstein1/html/index.html) die `&uuml` beim Laden im Browser nicht als ü dargestellt werden, ein `ü` im Quellcode allerdings schon. Wie sollen wir weiter vorgehen?

**Comment by lucas2412** [comment]
Bei mir wird alles korrekt im Browser angezeigt.

**Comment by martinakraus** [comment]
eben im Chrome und FF getestet (btw beides bessere Browser als IE ;) )
Funktioniert alles.
Wuerde trotzdem empfehlen das encoding im header anzugeben :)
